/* OOZEONOMICS article store — plain data, one object per article.
   Seed articles are drafted by the facility from live data (numbers checked
   against data/latest.json and the backtest). Operator articles mix in here.
   Fields: slug, cat (report|incident|explainer|manual), date, title, dek,
   keyPoints[], body[] (paragraphs; lines starting "## " render as h3). */
window.ARTICLES = [
{slug:'june-2026-seal',cat:'report',month:'2026-06',date:'2026-07-24',title:'June seals at {{s:2026-06}}: the jar drains 3 points',
 dek:'Gas and inflation eased at the same time — the biggest one-month relief since the winter.',
 keyPoints:[
  'The June 2026 Ooze Level sealed at {{s:2026-06}} (Sticky), down 3 points from May\'s {{s:2026-05}}.',
  'Gas pressure fell 11 points and inflation eased 9 — the two biggest movers.',
  'Employment remains the calmest line on the board at 14.'],
 body:[
  'The monthly specimen sealed in mid-July, once the jobs report and CPI landed, and the reading is the friendliest since spring: {{s:2026-06}} out of 100. That is Sticky territory — the band where normal economies live — and 3 points below May. June\'s reading is calmer than six of every ten months since 2003.',
  'The relief came from the two lines everyone feels first. Gas pressure dropped 11 points as pump prices steadied around $4.00, and inflation eased 9 as the yearly price change cooled to 3.5%. When the first link of the cascade relaxes, the whole chain breathes.',
  '## What\'s still pressing',
  'Housing remains the heaviest weight on the board — mortgage rates at 6.58% keep affordability pressure in the mid-40s. Auto-loan delinquency, on the truer New York Fed measure the lab now uses, reads hotter than the old proxy suggested. Credit card delinquency sits at 2.9% — higher than the unusually calm pandemic years, but not historically exceptional.',
  'Employment is the reason the jar stays calm. Unemployment held at 4.2%, and weekly jobless claims stayed quiet. Together they kept the employment line at just 14 — the calmest reading on the board. As the Lab Notes put it: recessions are employment events, and there isn\'t one in this data.',
  '## What a household would notice',
  'For most households, June probably felt a little easier than May. Filling the tank hurt less, grocery prices weren\'t rising as quickly, and steady employment kept paychecks coming. Housing remained the biggest source of strain, but for many families the month ended with a little more breathing room than it began.',
  'The next specimen seals in mid-August, when July\'s jobs report and CPI complete the month. The jar updates itself; you just check it.']},

  {slug:'oozemaxing-near-miss',cat:'incident',date:'2026-07-25',title:'2008 missed OOZEMAXING by exactly one line',
 dek:'The backtest found something nobody knew: even the Great Financial Crisis never tripped the everything-fails-at-once alarm.',
 keyPoints:[
  'OOZEMAXING requires all six weighted lines to read 60+ simultaneously. It has never happened in the comparable record since 2003.',
  'At the GFC\'s worst (June 2009), five of six lines crossed 60.',
  'The holdout was inflation — deflation held the line at 55 and kept the declaration off the board.'],
 body:[
  'When the facility defined OOZEMAXING — the breadth condition where every weighted intake line reads elevated at once — we assumed 2008 had obviously met it. Then we ran the numbers.',
  'June 2009, the worst month in the backtest, scores a calibrated 90: credit at 90, housing at 87, autos at 85, employment at 78, gas at 62. Five of six lines deep in failure. And the sixth?',
  '## The line that held',
  'Inflation — at stress 55. Not because prices were stable, but because they were falling. Deflation is its own kind of economic sickness, and the U-shaped inflation curve scores it as stress — but at 55, five points shy of the threshold. The Great Financial Crisis, the collapse that defines this meter\'s ceiling, missed the total-failure condition by one line and five points.',
  'That is why the facility can say something no other economic dashboard can: OOZEMAXING has never been declared. Not in 2008. Not in 2020. If this facility ever declares it, it will not be hype — it will be a first in modern history.',
  'Every number in this file is reproducible from the public backtest. Check us.']},

{slug:'vibecession-measured',cat:'explainer',date:'2026-07-25',title:'The vibecession, measured: why 2022 only scored {{peak:2022-01..2022-12}}',
 dek:'Everyone hated that economy. The cascade data says households mostly held. Both things are true.',
 keyPoints:[
  'The 2022 inflation surge peaked with CPI at 9.1% — the fastest since 1981.',
  'The Ooze peaked at just {{peak:2022-01..2022-12}} that year — within a few points of recent readings.',
  'The gap between feelings and cascade data is what "vibecession" actually means.'],
 body:[
  'June 2022: inflation hits 9.1%, gas passes $5, consumer sentiment prints its worst reading ever recorded. And the Ooze Level reads... {{s:2022-06}}.',
  'That number offends people. It felt so much worse. But the meter doesn\'t measure feelings — it measures the cascade: are households missing payments, losing cars, losing jobs, losing homes? In 2022, mostly, they weren\'t. Unemployment sat under 4%. Delinquencies were near record lows, still suppressed by pandemic savings. The bills were infuriating, and they were getting paid.',
  '## What the gap teaches',
  'Economists later named the phenomenon a vibecession — sentiment collapsing while the real economy held. OOZEMeter\'s 2022 reading is that concept with a number on it. The anger was real; the cascade failure never came. Prices are a tax on happiness before they are a tax on solvency.',
  'This is the meter\'s core discipline, and it cuts both ways: it refused to panic in 2022, and it refused to celebrate in April 2010, when the reading was still elevated at {{s:2010-04}} while headlines had moved on. Feelings lead; the cascade lags; the jar reports the cascade.']},

{slug:'what-is-oozeonomics',cat:'manual',date:'2026-07-26',title:'What is Oozeonomics?',
 dek:'The study of economic slime: how stress actually moves through household budgets, measured instead of narrated.',
 keyPoints:[
  'Oozeonomics is the facility\'s discipline: economics through the cascade, in plain language, from public data.',
  'Core doctrine: markets are not the economy; feelings are not the cascade; every number must be reproducible.',
  'This section mixes facility reports (from live data) with operator dispatches.'],
 body:[
  'Economics has a translation problem. The data lives in government spreadsheets; the narration lives in headlines optimized for alarm. Between them, a person just trying to answer "how bad is it, actually?" gets either jargon or panic.',
  'Oozeonomics is the facility\'s answer: study the slime. Follow stress the way it actually travels through a household — gas to credit card to car to job to house — and measure each link with public data anyone can check.',
  '## The three laws',
  'First: markets are not the economy. The dot-com crash vaporized trillions and the cascade barely moved; that is why there is no stock ticker in the formula. Second: feelings are not the cascade. 2022 proved a nation can be furious while solvent. Third: every number is reproducible. The anchors are published, the calibration is published, and any journalist with a free FRED key can rebuild the score to the digit.',
  'What appears in this section: monthly Specimen Reports when each reading seals, Incident Files when history gets re-examined, and explainers that turn one confusing economic idea at a time into plain language. Facility-drafted pieces are generated from live data and checked against it; operator dispatches are marked as such.',
  'The economy is a specimen. Watch it with us.']},

{slug:'ooze-report-2026-08-04',cat:'report',month:'2026-06',date:'2026-08-04',
 auto:true,byline:'Drafted with AI · approved by the operator · Division of Economic Containment',
 title:'The Ooze Report: {{s:2026-06}} out of 100, and eleven ounces running on January',
 dek:'June sealed at {{s:2026-06}}. The relief came from the two prices you actually watch; the expensive things did not move. Plus: two corrections, and what we cannot yet measure.',
 keyPoints:[
  'June sealed at {{s:2026-06}}/100 — Sticky, three points lighter than May, and calmer than six of every ten months since 2003.',
  'Housing, credit cards and auto loans carry 17 of the month\'s 26 ounces, and none of them moved.',
  'Eleven of those ounces rest on delinquency data last observed on January 1 — the newest figures that exist, and seven months old.'],
 body:[
  'Twenty-six out of a hundred. That is June, sealed — Sticky, the band where normal economies live, and three points lighter than May.',
  'Another way to hold it: June was calmer than six of every ten months since 2003. Not good, exactly. Just better than most of what we have measured.',
  '## The relief came from the two prices you actually watch',
  'Gas pressure fell further than any other line on the board in June, and inflation was not far behind. Those are the two costs a household meets on purpose — one at the pump twice a week, one at the register every time. When the visible prices ease, the month feels lighter. That is most of your three points right there.',
  '## The expensive things did not move',
  'Housing and credit-card debt each account for 6 of the month\'s 26 ounces. Car loans take another 5. That is 17 of 26 sitting on the three bills nobody renegotiates in a week, and none of them budged. So June improved the way a good week improves a hard month. The pump got kinder. The mortgage did not.',
  'Employment is the quiet one. Unemployment held at 4.2%, and that maps to a low enough reading that the heaviest-weighted line in the entire formula contributes just 3 of the 26 ounces — less than gas, and well under any of the three big bills. Recessions are employment events. This board is not showing one.',
  '## Eleven of those ounces are running on January',
  'Worth knowing before you trust the number too far. Credit-card and auto delinquency report quarterly, and neither has published since New Year\'s Day. Their figures — 2.9% and 7.7% — are the newest that exist anywhere, and they are seven months old. Together they carry 11 of the month\'s 26 ounces.',
  'Which means the jar genuinely cannot tell you what happened to household credit this spring. Nobody can. We would rather say so than let a confident number stand in for one we do not have.',
  '## Where things stand right now',
  'The seal is June, but a few numbers have moved since. At the end of July the pump was $4.10 a gallon, and the 30-year mortgage was 6.66%. Those are current levels, not June\'s — they will feed the July seal, which lands when the jobs report and CPI do.',
  'One limit, stated plainly: we store month-to-month change, not week-to-week. So we can tell you where a price stands, but not how far it travelled in the last seven days. That gets fixed on our side, not yours.',
  '## Markets are jumpier than kitchens',
  'Ward M — the market wing, experimental, and it never enters the number above — reads 37. Four of its six gauges cooled: oil at $80 a barrel, the VIX averaging 17.1, credit conditions loose, the yield curve positive at 0.73pp. The dollar ticked the other way.',
  'The interesting one is breadth, which measures how much of the market is weakening at once. It is the hottest gauge on the panel at 50 out of 100 — six tickers steady, four softening, one stressed. We cannot tell you how far it moved this week, because of a bug in how we store last week\'s reading. We are not going to round that to zero and call it flat, which is what we did last week and got wrong.',
  'Ward 37 against a household 26 is not a fair comparison — the ward is on July evidence, the jar is sealed at June. On the one month they both cover, June, the ward read 30 and the jar read {{s:2026-06}}. Markets were carrying more than kitchens were.',
  'The two instruments are never averaged. They share exactly one input, the Chicago Fed\'s financial-conditions index, which carries 3% of the household score. Worth saying out loud so nobody discovers it and assumes we were hiding it.',
  '## Corrections',
  'Two things in the previous edition were wrong, and both are our fault.',
  '<b>We said market breadth was unchanged.</b> It was not measured. Our collector compares each new reading against a file it then overwrites, so it produced a zero instead of an answer, and we printed the zero as if it meant something. Breadth is also the reason Ward M reads 37 rather than roughly 28 — so calling it flat did not just miss a number, it missed the story. The collector still is not fixed. That work is open and listed publicly.',
  '<b>We reported June without saying it used to read 27.</b> On August 1 we changed our own formula: a seventh line went in, the other six were rescaled, and the whole archive was recalculated. That moved 180 of 281 months by up to two points and changed nine band labels.',
  'We should have led with that. A number that changed because we changed the ruler is a different thing from a number that changed because the economy did, and you cannot tell them apart unless we say which happened. The full record is public in <a href="data/revisions.json">data/revisions.json</a>.',
  '## Who wrote this',
  'A language model drafted this edition from an evidence packet it cannot edit and a score it cannot compute. Every figure in it was checked against that packet, and the operator approved it before publication. That is a different thing from our Specimen Reports, which are generated by OOZEBOT — a deterministic script with no model in the path — and signed as such. The three categories are spelled out in the <a href="policies.html">editorial policy</a>.',
  'Two notes on units, because they are easy to mix up. A line\'s pressure moving 11 points is a change inside that line\'s own 0-to-100 reading; it is not subtracted from the headline. And ounces are how much each line contributes to the score — the seven weighted lines split June\'s 26 ounces and sum to exactly 26.']},

{slug:'correction-2026-08-archive-ounces',cat:'incident',date:'2026-08-02',title:'Correction: the archive printed ounces that did not sum to the reading',
 dek:'For roughly two hours on 2 August 2026, all eleven household archive reconstructions printed contribution figures on the wrong scale. The parts exceeded the whole by 7 to 11 ounces. Here is what happened and what changed in the machine.',
 keyPoints:[
  'Affected: all 11 household archive reconstructions (July 2025 through June 2026), live 2 August 2026 for about two hours.',
  'The bug: contributions were computed before calibration and printed against a post-calibration denominator, so the seven lines summed to 31-36 against a printed reading of 19-29.',
  'Fixed by apportioning the calibrated score by largest remainder — the same method the live collector uses — with an assertion that now fails the build if the parts ever miss the whole again.'],
 body:[
  'This file documents an error the facility published. It is here because a facility that prints its gaps and hides its mistakes is only half honest, and the half it keeps is the easy one.',
  '## What was wrong',
  'Every household archive reconstruction contains a sentence of the form "Housing carried the most weight — 9 of the month\'s 24 ounces." The denominator was the published Ooze Score. The numerator was not a share of it. Contributions were computed as weight times line stress, which is the figure the formula uses <em>before</em> calibration maps it onto the published 0-100 scale. Printed together, they described a part-of-whole whose parts exceeded the whole by 25 to 45 percent in all eleven reports.',
  'A reader with a calculator and the published weights would have found it, which is the point: every one of those reports closes by inviting exactly that check. The invitation was real and the arithmetic was wrong.',
  '## What was not wrong',
  'The Ooze Scores themselves. Every headline reading, band, delta, and historical percentile in the archive was and remains correct — those come from the calibrated pipeline and were independently re-derived and asserted against the published backtest before publication. The defect was confined to how each line\'s share of the total was displayed. The live monthly seal was never affected; its collector has apportioned contributions correctly, with an assertion, since it was written.',
  '## What changed in the machine',
  'The archive generator now apportions the calibrated score across the seven weighted lines by largest remainder — the identical method the live collector uses, so the two engines cannot describe the same month differently. A hard assertion compares the sum of the parts to the printed reading and stops the build if they ever differ. Three further defects found in the same review were fixed alongside it: reports were stamped with dates inside the month they described rather than the date they were computed, plural line names took singular verbs in three months, and two lines tied for heaviest were printed as though one outranked the other.',
  '## Why this file exists',
  'The facility\'s rule is that missing evidence is editorial content. The same applies to wrong evidence. A correction that is quietly patched teaches a reader nothing about whether the next number can be trusted; a correction that is published, dated, and explained is the only evidence a reader ever gets that the checking is real.',
  'The corrected archive is republished. Every figure in it recomputes from the public backtest — and now the ounces sum to the reading they are quoted against.']},

{slug:'gas-prices-explained',cat:'explainer',date:'2026-08-02',title:'Gas prices: the number America reads twice a week',
 dek:"Posted in foot-tall numbers on every corner, paid on a schedule nobody chooses — why the pump is the economy's mood ring, and how the facility meters it.",
 keyPoints:[
  'Gas is the most visible price in American life — it moves household mood faster than any statistic.',
  "Crude oil is roughly half the pump price; refining, distribution, taxes, and season split the rest.",
  'The facility meters the EIA\'s weekly national average, inflation-adjusted before it becomes stress.'],
 body:[
  'No other price in American life gets this treatment: posted in foot-tall numbers on every corner, checked twice a week by almost every adult, paid on a schedule nobody chooses. When gas rises, the pain is immediate — commuters, delivery businesses, and family budgets feel it within days. That visibility is why economists watch it even though fuel is a modest slice of total spending: gas prices move household *mood* faster than any other statistic.',
  '## What actually sets the price',
  "Crude oil is roughly half of what you pay at the pump, so global oil markets drive most moves. The rest splits between refining capacity, distribution, taxes, and season — summer blends and road-trip demand push prices up most years, and a single refinery outage can move a whole region. Which is also why no president controls gas prices: policy can nudge at the margins with reserves, permits, and taxes, but no administration sets the number on the sign.",
  '## Why it leads the cascade',
  "In the facility's cascade model, gas is step one — the first pressure every budget feels, impossible to skip, and a cost that leaks into the price of nearly everything that moves on a truck. When fuel gets expensive, the gap between paycheck and prices opens first here, and the overflow lands on the credit card. That is why the gas line carries a fast, weekly cadence while most lines refresh monthly or quarterly.",
  '## The 2008 benchmark',
  "In June 2008 the national average hit $4.11 — a record that, adjusted for inflation, still stings. Expensive fuel arrived at the exact moment the housing collapse was destroying household wealth, squeezing budgets from both sides. The facility's incident files keep that month as the gas line's reference point for what a genuine fuel emergency looks like.",
  '## How the facility meters it',
  "The collector reads the EIA's weekly U.S. regular-gasoline average (series GASREGW via FRED), adjusts historical comparisons for inflation using CPI, and maps the result onto published anchor points to produce a 0–100 stress reading. The anchors are public, the source is one click from the gauge, and the current reading — with its as-of date — is always on the gas intake line's own page. No forecasts: the line reports what fuel costs now, not where it is headed.",
  'See the live reading, its history notes, and the full FAQ on the gas intake line — or check the pump on your corner, which is the original data source.'],
},

{slug:'housing-explained',cat:'explainer',date:'2026-08-02',title:'Housing: the biggest bill and the biggest asset, at the same time',
 dek:'Most families\' largest monthly payment is also their largest store of wealth. When mortgage rates climb, the whole chain slows — and history says this line deserves its thick pipe.',
 keyPoints:[
  'Housing is most households\' biggest bill and biggest asset simultaneously — stress here transmits everywhere.',
  'Mortgage rates follow the 10-year Treasury yield plus a spread; the Fed moves them only indirectly.',
  'Housing led the economy into the 2008 crisis; today\'s stress is affordability, not credit quality.'],
 body:[
  "Housing occupies a place no other line does: for most families it is the biggest monthly bill and the biggest asset at the same time. When mortgage rates climb, affordability collapses for buyers and the whole chain slows — fewer sales, less construction, less spending on everything that fills a house. And because home equity is most households' main store of wealth, housing stress transmits into confidence, retirement plans, and the willingness to spend anywhere else.",
  '## What moves mortgage rates',
  "Mostly the 10-year Treasury yield plus a spread. When investors expect inflation, or the Federal Reserve holds short rates high, Treasury yields rise and mortgages follow. That is why mortgage rates can climb even when the Fed does nothing — and why they sometimes ease before the Fed cuts. The facility meters the 30-year fixed rate from Freddie Mac's weekly survey, the standard benchmark since 1971.",
  '## The 2008 incident file',
  "In 2008, this line ruptured. Subprime lending, teaser rates, and speculation sent prices to unsustainable heights; the collapse erased roughly $7 trillion in home equity and triggered a global financial crisis. The Ooze Score's own history shows the damage: the overall reading peaked near {{peak:2008-01..2009-12}} during that episode, and housing was the heaviest contributor for months.",
  '## Is today like 2008?',
  "The stress source differs, and the facility keeps the distinction visible. 2008 was a credit-quality crisis — loans that should never have been written. Today is an affordability crisis — solid loans that few can afford to originate, because prices and rates rose together. Painful, but structurally safer: lending standards are far stricter and household equity far stronger. An affordability squeeze grinds; a credit collapse breaks.",
  '## In the cascade',
  "Housing is the cascade's terminal stage — the house is last to fall, because families defend the mortgage payment beyond every other bill. That is exactly why the housing line gets one of the heaviest weights in the formula: by the time this line is screaming, every earlier defense has already failed. A separate zero-weight auxiliary sensor tracks mortgage delinquency as the distress confirmation.",
  'The live rate, its as-of date, and the full methodology are on the housing intake line — every figure one click from Freddie Mac\'s own published survey.'],
},

{slug:'credit-cards-explained',cat:'explainer',date:'2026-08-02',title:'Credit cards: the economy\'s smoke detector',
 dek:'Cards are the first bill households skip when budgets crack. Rising delinquency means kitchen-table budgets are failing months before any headline says so.',
 keyPoints:[
  'Card delinquency is an early-warning signal: the first payment skipped when budgets crack.',
  'Balances rise when essentials outrun paychecks — at record APRs above 21%, the gap compounds fast.',
  'Delinquency at 30 days is the tremor; charge-offs are the earthquake confirmation, quarters later.'],
 body:[
  "Credit card stress is the economy's early-warning smoke detector. Cards are the first bill households skip when budgets crack — before the car payment, long before the mortgage. So when delinquencies rise, it means millions of kitchen-table budgets are already failing, months before that failure shows up in unemployment or foreclosure statistics. The facility gives this line a heavy weight for exactly that reason: it is where household distress appears first.",
  '## The mechanics of the squeeze',
  "A delinquency is a payment more than 30 days late; at 90 days it becomes serious, and when the bank gives up collecting, a charge-off. Balances climb when the price of essentials outruns paychecks and families bridge the gap on the card — at APRs above 21%, the highest on record, which makes every bridged month more expensive than the last. America's card balance crossed $1.1 trillion in nominal terms, an all-time high, though as a share of income it remains below the 2008 peak.",
  '## What 2008 taught the gauge',
  "Charge-off rates peaked above 10% in 2010 as unemployment destroyed household finances — the smoke detector confirmed the fire, but late: charge-offs lag the original missed payments by quarters. That is why the facility meters the earlier signal, the delinquency transition rate from the NY Fed's Household Debt and Credit report, rather than waiting for the charge-off confirmation.",
  '## Reading it honestly',
  "One quarter of rising delinquency is noise; a steady climb from a low base is exactly the trend this facility exists to catch. The line's stress score maps the delinquency rate onto published anchors calibrated against two decades of history — including the pandemic-era lows that made any normalization look dramatic. The gauge tells you where the line sits against history, not where it is going.",
  'The current reading, its quarterly cadence, and the full FAQ live on the credit intake line — sourced from the NY Fed\'s public workbook, one click away.'],
},

{slug:'auto-loans-explained',cat:'explainer',date:'2026-08-02',title:'Auto loans: the most defended payment in the budget',
 dek:'In most of America, no car means no job. When auto delinquencies rise, the stress has already burned through every other line of defense.',
 keyPoints:[
  'Families pay the car before the credit card — sometimes before the rent. No car, no job.',
  'Payments hit records via three compounding forces: prices up ~30%, rates doubled, terms stretched.',
  'Rising auto delinquency signals deep distress precisely because this payment is defended hardest.'],
 body:[
  "In most of America, no car means no job. That single fact makes the auto loan the most defended payment in the household budget — families pay the car before the credit card, sometimes before the rent, because losing the car means losing the income that pays everything else. So when auto delinquencies and repossessions rise, it signals stress that has already burned through every other line of defense. The cascade model puts the breaking car payment at step four: past the point where cushions exist.",
  '## Why payments hit records',
  "Three compounding forces. Vehicle prices jumped roughly 30% since 2020; interest rates roughly doubled; and buyers stretched to longer terms — seven-year loans that lower the monthly payment while raising the total cost and leaving borrowers owing more than the car is worth for years. The average new-car payment now exceeds $730 a month, a record. EV depreciation has been unusually steep, adding a new pocket of underwater borrowers the facility is monitoring.",
  '## The 2008–09 reference',
  "Repossessions surged past 1.9 million in 2009 — the terminal confirmation of that era's household collapse. A repossession typically follows 60–90 days of missed payments and craters the borrower's credit for years, which is why families fight so hard to avoid it, and why the numbers only move when things are genuinely bad.",
  '## How the facility meters it',
  "The line uses the NY Fed's auto-specific 30+ day delinquency transition series — a deliberate methodology upgrade from the broad consumer-loan proxy used in v1, recorded publicly in the methodology version history. Quarterly cadence, published anchors, and a stress score that reads against two decades of history. When this gauge climbs while credit cards climb too, the cascade is moving in order; when it climbs alone, something unusual is happening in vehicle finance itself.",
  'The live reading and its lineage are on the auto intake line — with the methodology change that improved it documented in the public revision record.'],
},

{slug:'unemployment-explained',cat:'explainer',date:'2026-08-02',title:'Unemployment: the heaviest line in the jar',
 dek:'Every other pressure is survivable with a paycheck. This is the line that turns a squeeze into a crisis — and why it carries the formula\'s largest weight.',
 keyPoints:[
  'A paycheck makes every other pressure survivable — which is why employment carries the largest weight.',
  'The facility pairs the monthly unemployment rate with weekly jobless claims as a fast shock detector.',
  'Claims momentum caught the 2020 collapse weeks before the monthly rate confirmed it.'],
 body:[
  "Every other line in the jar measures a squeeze. This one measures the break. Expensive gas, heavy card balances, a brutal car payment — all survivable with a paycheck. Remove the paycheck and every one of them fails at once, which is the cascade's fifth step: no car, no job; no job, no mortgage payment. That is why employment carries the largest weight in the formula, and why no honest economic stress measure can treat it as just another statistic.",
  '## Two speeds, one line',
  "The headline unemployment rate is monthly, revised, and slow — real crises move faster than its calendar. So the facility's employment line pairs the monthly rate with initial jobless claims, reported weekly, as a shock detector. The claims-momentum term exists because of a specific historical failure: in March 2020, claims exploded from about 200,000 a week to 6.9 million in three weeks, while the monthly unemployment rate was still printing a decades-low number. Weekly claims caught the collapse first; the facility's own history shows the score jumping from {{s:2020-02}} to {{s:2020-03}} in a single month.",
  '## Reading it against history',
  "The score's archive puts employment stress in context: the 2008–09 episode ground upward for two years as unemployment doubled, while 2020 was a vertical shock followed by a fast retreat. Same gauge, two different disasters — one slow-burning credit collapse, one sudden stop. The employment line's anchors are calibrated so both read as the emergencies they were.",
  '## What it cannot tell you',
  "Unemployment is a lagging confirmation in slow downturns — employers cut hours, freeze hiring, and burn through attrition before layoffs begin. That is why the jar carries earlier-warning lines (credit delinquency, and as of methodology v3, financial conditions) ahead of it in the cascade. When employment finally moves, the earlier lines have usually been elevated for months.",
  'The live rate, weekly claims reading, and full methodology are on the unemployment intake line — both series public, both one click from their federal sources.'],
},

{slug:'inflation-explained',cat:'explainer',date:'2026-08-02',title:'Inflation: the pressure that makes every other line heavier',
 dek:'Inflation is not one price rising — it is the ruler shrinking. How the facility meters purchasing power, and why deflation once kept a declaration off the board.',
 keyPoints:[
  'Inflation compounds every other pressure: the same paycheck buys less of everything at once.',
  'The facility meters year-over-year CPI — the change in the ruler, not any single price.',
  'In June 2009, deflation held the inflation line calm — the one line that kept OOZEMAXING off the board.'],
 body:[
  "Inflation is different from every other line in the jar. Gas is a price; housing is a payment; inflation is the ruler itself shrinking. When yearly price growth runs hot, the same paycheck buys less of everything simultaneously — which makes every other pressure heavier at once. A manageable card balance becomes unmanageable, a tight budget becomes impossible, and the squeeze arrives without any single bill being to blame.",
  '## What the gauge actually measures',
  "The facility meters year-over-year change in the Consumer Price Index — the Bureau of Labor Statistics' basket of what urban households actually buy — using the unadjusted series, with the adjustment basis frozen and published in the methodology. Year-over-year is a deliberate choice: it mutes monthly noise and seasonal wiggle, at the cost of reacting a little slower to turning points. The facility accepts that trade because the jar measures sustained pressure, not headlines.",
  '## The strange incident of 2009',
  "The facility's OOZEMAXING condition — every weighted line elevated at once — has never been met in the comparable record. Its nearest miss reveals inflation's odd role: at the crisis peak of June 2009, with the overall score at {{s:2009-06}}, five of six lines had crossed the emergency threshold. The one holdout was inflation — because prices were *falling*. Deflation, itself a symptom of collapsing demand, technically kept the board from declaring a total cascade. The gauge records what prices did, not whether the reason was comforting.",
  '## High, low, and the uncomfortable middle',
  "Very high inflation is obvious stress. Deflation is a different emergency wearing a friendly face. The uncomfortable middle — inflation cooling from a spike while its level still stings — is where public mood and measured rates disagree most, because households remember what things used to cost long after the rate of change improves. The facility's vibecession incident file documents exactly that gap between the measured jar and the national mood.",
  'The current year-over-year reading and its BLS source are on the inflation intake line, refreshed each month when CPI lands — the release that, with the jobs report, seals each monthly specimen.'],
},

{slug:'financial-conditions-explained',cat:'explainer',date:'2026-08-02',title:'Financial Conditions: the plumbing gauge — and the bet behind it',
 dek:'The jar\'s seventh line reads the financial system\'s plumbing through 105 indicators. It entered at 3% as a labeled bet, and this is the full disclosure.',
 keyPoints:[
  'The NFCI compresses 105 measures of lending, funding, and risk appetite into one weekly number.',
  'It entered the flagship at 3% in methodology v3 — a labeled bet on credit-driven crises.',
  'Full disclosure: its backtested benefit comes from one historical episode, and it dilutes slightly in calm markets.'],
 body:[
  "In methodology v3, the jar gained a seventh intake line — and because this facility does not add numbers quietly, this article is the plain-English version of the full disclosure. Financial Conditions reads the Chicago Fed's National Financial Conditions Index: 105 measures of lending, funding, and risk appetite across banks and shadow banks, compressed into one weekly number. Positive means tighter than normal — credit harder to get; negative means looser. It is the closest thing the jar has to a gauge on the economy's plumbing.",
  '## Why credit conditions belong in a household meter',
  "Because tight plumbing reaches kitchens eventually. When funding markets seize, the damage travels: banks pull back, loans get denied, rates rise, hiring slows, and months later the household lines confirm what the plumbing knew first. In the slow credit tightening of 2007–08, financial conditions deteriorated well before unemployment moved — the score's own archive shows the long grind from {{s:2007-06}} in mid-2007 to {{peak:2008-01..2009-12}} at the crisis peak.",
  '## The bet, stated plainly',
  "This line is a bet, and the facility labels it as one. In backtesting, a 3% financial-conditions weight made the score climb about a month earlier during 2007–08's slow tightening — and did nothing in the fast crash of 2020, when everything moved at once. Its measured benefit comes from that single historical episode: remove 2007–09 from the record and the benefit disappears. In calm markets its arithmetic effect on the blended score is slightly negative. It was weighted at 3% because that is the smallest weight where the early warning is visible and the largest where every score movement still has a household explanation.",
  '## What it is not',
  "It is not the stock market. The S&P 500 is not an input to the Ooze Score at any weight — that question was studied at length, and the decision record with four backtested studies is public. Markets get their own separate instrument, Ward M, which never touches this score. And like every line in the facility: no forecasts. The gauge reports conditions now.",
  'The live reading is on the financial conditions intake line; the full studies, the weight optimization, and the sensitivity test that failed are all public in the research archive — because a bet you can\'t audit is just a guess.'],
},

{slug:'foreclosures-aux-explained',cat:'explainer',date:'2026-08-02',title:'The foreclosure line: why the cascade\'s terminal stage reads AUX',
 dek:'Every filing is a family that ran out of every option. So why does this line carry zero weight? A case study in honest proxies.',
 keyPoints:[
  'Foreclosure is the cascade\'s terminal stage — every filing is a family that exhausted every defense.',
  'No clean public national foreclosure-filings series exists on an open path — so the facility uses a labeled proxy.',
  'The proxy (mortgage delinquency) carries zero weight because housing already counts that distress.'],
 body:[
  "Foreclosure is the cascade's final step — the house is last to fall, and every filing represents a family that ran out of every option above it: the savings, the cards, the car, the job. A line that important would seem to deserve a heavy weight in the formula. Instead it reads AUX · 0-WEIGHT on the board. The reason is a small case study in how this facility handles data honestly.",
  '## The data problem',
  "There is no consistent, public, national foreclosure-filings series available through an open acquisition path. The comprehensive counts are proprietary (paid real-estate data vendors); the free alternatives are partial or discontinued. The facility's options were: pay for data it cannot republish, scrape something it shouldn't, fake it — or use a disclosed proxy. It uses the proxy: the Federal Reserve's single-family mortgage delinquency rate, which tracks the same distress one stage earlier.",
  '## Why zero weight',
  "Because mortgage delinquency already informs the housing line's stress reading. Giving the proxy its own weight would count the same suffering twice and quietly inflate the score — the kind of small dishonesty that compounds. So the line rides along at zero weight, visible because the terminal stage of the cascade deserves a gauge, labeled AUX everywhere it renders so nobody mistakes a proxy for a count.",
  '## What it showed in 2008',
  "Mortgage delinquency surged through the crisis, confirming the borrower distress that produced millions of actual foreclosures — the proxy and the reality moved together, which is what makes it a usable stand-in. But the facility keeps the distinction explicit: delinquency is not a filing, a filing is not an eviction, and a gauge that blurs those lines would flunk its own audit.",
  "The proxy's live reading and full limitations are on the foreclosures intake line. If a clean public filings series ever exists, the ledger has a standing task to wire it — until then, the label tells the truth."],
},

{slug:'manufacturing-aux-explained',cat:'explainer',date:'2026-08-02',title:'The manufacturing sensor: the factory floor as early warning',
 dek:'Factories feel slowdowns before households do — orders vanish before paychecks. Why this classic signal rides at zero weight, on public data only.',
 keyPoints:[
  'Manufacturing slows before households feel it: orders vanish before paychecks do.',
  'The facility meters industrial production plus new orders — public Fed and Census data, not the licensed PMI.',
  'Zero weight until the sensor earns a place: auxiliary status is a probation, not a demotion.'],
 body:[
  "Factories feel a slowdown before households do. Orders get cancelled before shifts get cut; shifts get cut before layoffs begin; and by the time a manufacturing recession reaches the unemployment line, the factory floor has been signaling for months. That makes manufacturing a classic early-warning input for any economic gauge — and the facility's version of it a deliberate exercise in doing early warning honestly.",
  '## What it meters, and what it refuses to',
  "The sensor combines industrial production (the Federal Reserve's monthly output index) with manufacturers' new orders from the Census Bureau — both public, both citable, both free to display. What it deliberately does not use is the famous ISM Purchasing Managers' Index: PMI is licensed data, and this facility does not scrape or republish what it has no rights to. The lesson file documents the free data path in full, precisely so anyone can rebuild the sensor.",
  '## Why auxiliary status',
  "The line rides at zero weight. Not because the signal is worthless — because it has not yet earned a weighted place under the facility's rules: every weighted line needs a backtested justification, published anchors, and a demonstrated relationship to household stress that is not already counted by an existing line. Manufacturing employment is a shrinking share of American work, and the link between factory orders and kitchen-table pressure is real but indirect. Until the case is made publicly, the sensor stays on the board, visible, labeled AUX, contributing nothing.",
  '## The probation system',
  "This is the same discipline that governs the whole jar: sensors audition in public. Foreclosures rides as a labeled proxy; manufacturing rides as a labeled auxiliary; four market gauges were parked into the improvements ledger when Ward M slimmed to six. The alternative — quietly adding lines because they feel important — is how a trustworthy number becomes a vibes dashboard with extra steps.",
  'The sensor\'s live readings and its complete free-data path are on the manufacturing intake line, with the licensed-data boundary documented in its lesson file.'],
},

{slug:'how-the-score-works',cat:'explainer',date:'2026-08-02',title:'How the Ooze Score works: the whole recipe in plain English',
 dek:'Seven lines, fixed weights, published anchors, one calibration rule — and a robot that collects it daily. No black boxes, by construction.',
 keyPoints:[
  'Each line is scored 0–100 against fixed public anchors, then weighted; the weighted sum is the score.',
  'Calibration is pegged to lived history: the calmest modern month reads 10, the 2008–09 peak reads 90.',
  'The pipeline is public: a daily robot collects, an integrity gate verifies, and failures stop publication.'],
 body:[
  "The Ooze Score is one number built from seven, and every step between the government data and the jar is public. This is the whole recipe, in plain English — the lab-notes version exists too, with every constant, but nothing here is simplified into untruth.",
  '## Step one: each line becomes a stress reading',
  "Each intake line — gas, housing, credit cards, auto loans, unemployment, inflation, and financial conditions — produces a raw value from a cited public source. That raw value is mapped onto fixed, published anchor points to become a 0–100 stress reading. An anchor table says, in effect: this gas price historically meant calm, this one meant emergency. The anchors do not move with the news; changing any of them is a methodology revision, logged publicly.",
  '## Step two: the weighted sum',
  "Each line's stress multiplies its fixed weight — employment heaviest, then housing and credit, then autos, then gas and inflation, with financial conditions at a deliberate 3% — and the weighted contributions sum to the headline. The weights are published to the decimal and sum to exactly 100. When you see 'Housing 6 oz' in a report, that is housing's weighted contribution to the month's total ounces of ooze.",
  '## Step three: calibration to lived history',
  "The raw sum is then calibrated so the scale means something human: the calmest month of the modern record reads 10, and the worst month of the 2008–09 crisis reads 90. Nothing is tuned to make today look better or worse — the calibration constants froze against history and are re-derived only when methodology changes, on the public record. Today's reading always answers: where does now sit between the best and worst months in memory?",
  '## Step four: the robot and the gate',
  "A collector runs daily in public view, refreshing each line as its source releases and sealing the headline once a month when the jobs report and CPI land. Before anything publishes, an integrity gate checks every value against plausibility bounds and verifies the calibration still holds — and if any check fails, the site keeps the previous good reading and the pipeline stops until a human looks. When sources revise their own history, the revision is detected and logged publicly rather than silently absorbed.",
  "Every claim above is verifiable: the code, the anchors, the calibration, and every day's data live in the public repository. The score's entire authority rests on that — anyone with a free FRED key can rebuild the number to the digit, and the facility considers that a feature, not a threat."],
},

{slug:'reading-the-bands',cat:'explainer',date:'2026-08-02',title:'SMOOTH to OVERFLOWING: what each band of the meter feels like',
 dek:'A number needs a scale that means something. The five bands, what each feels like at the kitchen table, and the ☢ condition that has never been met.',
 keyPoints:[
  'Five bands, pegged to history: the calmest modern month reads 10, the 2008–09 peak reads 90.',
  'STICKY (21–40) is where normal economies live — pressure visible in data before headlines.',
  'OOZEMAXING is a breadth condition, not a band — every line failing at once, never yet met.'],
 body:[
  "A number without a scale is a decoration. The Ooze Score's five bands exist so that any reading translates instantly into something felt — and because the scale is pegged to the historical record rather than opinion, each band corresponds to months that actually happened.",
  '## 🟢 SMOOTH (0–20)',
  "Budgets bend without breaking. Pressure exists — it always does — but savings absorb it. The calmest stretch of the modern record lived here: the late-2010s expansion bottomed the meter out near {{s:2019-10}}. If the jar reads SMOOTH, complaints about the economy are real but local, not systemic.",
  '## 🟡 STICKY (21–40)',
  "Where normal economies spend most of their time. The pressure shows in the data before it makes headlines: balances creep, savings thin, the paycheck-to-prices gap goes on the card. Most months since 2003 have been STICKY or better — which is worth remembering when every headline sounds like an emergency.",
  '## 🟠 SLIPPERY (41–60)',
  "Softening becomes slipping. Delinquencies rise, hiring slows, and households cut real things — not luxuries, logistics. The pandemic shock of spring 2020 spiked the meter into this territory ({{s:2020-03}} at its worst month) before the fastest retreat in the record.",
  '## 🟠 OOZING (61–80) and 🔴 OVERFLOWING (81–100)',
  "Broad distress, then systemic crisis. Several lines failing at once, the cascade moving link to link — recession-grade territory and beyond. The 2008–09 collapse walked the meter through OOZING for months before peaking at {{peak:2008-01..2009-12}}, deep in OVERFLOWING. The calibration pegs that peak at 90 so the scale always remembers what a real emergency was.",
  '## ☢ The condition beyond the bands',
  "OOZEMAXING is not a band — it is a breadth condition, declared only when every weighted line reads elevated simultaneously. In the comparable record it has never been met: even at the 2009 peak, falling prices held the inflation line down and kept the declaration off the board. If this facility ever declares it, it will not be hype.",
  'Today\'s reading, marked in its band with the full legend, is always one tap from the score: the status chip on the front page links straight to the scale.'],
},

{slug:'ward-m-explained',cat:'explainer',date:'2026-08-02',title:'Ward M: why markets got their own jar instead of a seat in ours',
 dek:'The boss wanted the stock market in the score. The studies said no — and yes. The full story of the facility\'s market wing, and the divergence it exists to show.',
 keyPoints:[
  'Markets and household stress genuinely diverge — markets have panicked while households stayed fine, and led while data lagged.',
  'Four backtested studies said: don\'t blend market data into the household score — display it beside the jar.',
  'Ward M is a separate calibrated instrument: same doctrine (calm=10, GFC=90), zero weight in the Ooze Score.'],
 body:[
  "The most common question a household stress meter gets is some version of: what about the stock market? It is a fair question with a genuinely interesting answer, and this facility's version of it played out in public — a full review, four backtested studies, and a decision record anyone can read. The short version: markets earned their own instrument, not a seat in the household jar.",
  '## The honest case for markets',
  "Markets are forward-looking. Stocks fell before COVID was officially anywhere in the economic data, because companies warned about earnings while government statistics still looked pristine. Anyone who traded through that remembers: the market moved first, the data followed. A stress meter that ignores that entirely is leaving real information on the table.",
  '## The honest case against',
  "Markets also cry wolf — they have panicked repeatedly while households stayed fine, and rallied while households struggled. The divergence is the norm, not the exception: since 2003, months where markets sat near highs while household stress ran elevated outnumber the reverse by more than twenty to one. Blend a market signal into a household score at any meaningful weight and you import the market's mood swings into a number that is supposed to mean rent, gas, and groceries. The studies confirmed it: at every weight tested, the market component either did nothing or made the score less honest about households.",
  '## The resolution: two instruments, side by side',
  "So the facility built Ward M — a separate market-stress composite on its own 0–100 scale, calibrated by the same doctrine as the jar (its calmest month reads 10, its worst 2008 month reads 90), from six gauges: the bond market's recession signal, the fear gauge, a Federal Reserve credit index, oil, the dollar, and breadth across eleven verifiable tickers. It updates at market cadence, wears an EXPERIMENTAL badge, and contributes exactly zero to the Ooze Score. The one bridge between wings is deliberate and disclosed: the credit-conditions index entered the household formula at 3% in methodology v3, as a labeled bet documented in its own article.",
  '## The picture worth the whole wing',
  "The divergence chart on the ward's page draws both instruments across the same twenty years, and the story is visible at a glance: the ward screamed through 2020 and late 2022 while the household jar stayed comparatively calm. Two honest gauges, disagreeing when history disagreed — that disagreement is not a bug in either number. It is the most useful thing the market wing shows.",
  'Ward M lives at the Markets tab — composite, gauges, Sector Watch, and the divergence chart, with the full decision record linked from the page.'],
}
];
