const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repo = path.resolve(__dirname, '..');
const m = require(path.join(repo, 'scripts/lib/methodology'));
const notes = fs.readFileSync(path.join(repo, 'notes.html'), 'utf8');
const backtestSrc = fs.readFileSync(path.join(repo, 'scripts/backtest.js'), 'utf8');
const collectSrc = fs.readFileSync(path.join(repo, 'scripts/collect.js'), 'utf8');

const PUBLISHED = [
  ['Unemployment — UNRATE (%)', m.UNEMPLOYMENT_ANCHORS],
  ['Weekly claims — ICSA (thousands, trailing 4-week mean)', m.CLAIMS_K_ANCHORS],
  ['Inflation — CPI YoY (%)', m.INFLATION_YOY_ANCHORS],
  ['Mortgage rate (%)', m.MORTGAGE_RATE_ANCHORS],
  ['Mortgage delinquency (%)', m.MORTGAGE_DELINQ_ANCHORS],
  ['Card delinquency (%)', m.CARD_DELINQ_ANCHORS],
  ['Gas (real $/gal, deflated by CPI)', m.GAS_REAL_ANCHORS],
  ['Auto 30+ delinquency (%)', m.AUTO_30_PLUS_ANCHORS],
  ['Financial conditions (NFCI)', m.FINANCIAL_CONDITIONS_ANCHORS],
  ['Manufacturing — industrial production YoY (%)', m.MANUFACTURING_YOY_ANCHORS],
  ['Federal debt service — interest ÷ receipts (%)', m.DEBT_BURDEN_ANCHORS],
];

test('Lib Notes publish every anchor curve from the single source', () => {
  const tables = [...notes.matchAll(/<caption>([^<]*)<\/caption>[\s\S]*?<tbody>([\s\S]*?)<\/tbody>/g)];
  assert.equal(tables.length, PUBLISHED.length, `expected ${PUBLISHED.length} tables, found ${tables.length}`);
  const byCaption = new Map(tables.map((t) => [t[1].trim(), t[2]]));
  for (const [title, pts] of PUBLISHED) {
    const rows = byCaption.get(title);
    assert.ok(rows, `table missing: ${title}`);
    const parsed = [...rows.matchAll(/<tr><td>([^<]*)<\/td><td>([^<]*)<\/td><\/tr>/g)]
      .map((x) => [+x[1], +x[2]]);
    assert.deepEqual(parsed, pts, `table drifted from constants: ${title}`);
  }
});

test('interpolation goldens hold on the published unemployment curve', () => {
  const interp = m.interpolateAnchors;
  assert.equal(interp(m.UNEMPLOYMENT_ANCHORS, 5), 25);
  assert.equal(interp(m.UNEMPLOYMENT_ANCHORS, 6.5), 45);
  assert.equal(interp(m.UNEMPLOYMENT_ANCHORS, 8), 62);
  assert.equal(interp(m.UNEMPLOYMENT_ANCHORS, 10), 78);
  assert.equal(interp(m.UNEMPLOYMENT_ANCHORS, 25), 100);
});

test('collector and backtest consume the pooled anchors — no duplicated literals', () => {
  for (const [name, src] of [['backtest.js', backtestSrc], ['collect.js', collectSrc]]) {
    assert.doesNotMatch(src, /\[\[3\.5,5\],\[5,25\],\[6\.5,45\]/, `${name} still defines unemployment anchors`);
    assert.doesNotMatch(src, /\[\[200,5\],\[300,30\],\[400,60\]/, `${name} still defines claims anchors`);
    assert.match(src, /UNEMPLOYMENT_ANCHORS/, `${name} does not reference the pooled anchor`);
    assert.match(src, /MORTGAGE_DELINQ_ANCHORS/, `${name} does not reference the pooled anchor`);
  }
});

test('Lab Notes tables are generated, not hand-maintained', () => {
  assert.match(notes, /ANCHOR TABLES — generated by scripts\/build-notes\.js/);
  assert.match(notes, /id="anchorTables"/);
});
