#!/usr/bin/env node
/* Publishes the frozen anchor curves into Lab Notes as static tables — one
   source of truth (scripts/lib/methodology.js), no typed values.
   Run after the anchors change; tests/anchors-published.test.js fails if the
   tables drift from the constants. */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const m = require('./lib/methodology');

const TABLES = [
  ['Unemployment — UNRATE (%)', m.UNEMPLOYMENT_ANCHORS, 'the national employment line, and every state reading in the regional wing'],
  ['Weekly claims — ICSA (thousands, trailing 4-week mean)', m.CLAIMS_K_ANCHORS, 'the speed leg of the employment line'],
  ['Inflation — CPI YoY (%)', m.INFLATION_YOY_ANCHORS, 'not seasonally adjusted, same-month year-over-year'],
  ['Mortgage rate (%)', m.MORTGAGE_RATE_ANCHORS, '30-year fixed, Freddie Mac PMMS'],
  ['Mortgage delinquency (%)', m.MORTGAGE_DELINQ_ANCHORS, 'single-family at commercial banks — the housing line\'s second leg, also shown as the mortgage-distress sensor'],
  ['Card delinquency (%)', m.CARD_DELINQ_ANCHORS, 'credit-card loans at commercial banks'],
  ['Gas (real $/gal, deflated by CPI)', m.GAS_REAL_ANCHORS, 'nominal gas ÷ a CPI anchor — comparison across decades'],
  ['Auto 30+ delinquency (%)', m.AUTO_30_PLUS_ANCHORS, 'NY Fed household debt workbook'],
  ['Financial conditions (NFCI)', m.FINANCIAL_CONDITIONS_ANCHORS, 'Chicago Fed, calendar-month mean'],
  ['Manufacturing — industrial production YoY (%)', m.MANUFACTURING_YOY_ANCHORS, 'auxiliary, zero weight'],
  ['Federal debt service — interest ÷ receipts (%)', m.DEBT_BURDEN_ANCHORS, 'auxiliary, zero weight'],
];

const table = (title, pts, note) => `<table class="anchor-tab">
  <caption>${title}</caption>
  <thead><tr><th>value</th><th>stress</th></tr></thead>
  <tbody>${pts.map(([v, s]) => `<tr><td>${v}</td><td>${s}</td></tr>`).join('')}</tbody>
</table>
<p class="tab-note">${note} — points are linear between rows; the curve never extrapolates beyond its endpoints.</p>`;

const block = `<!-- ANCHOR TABLES — generated by scripts/build-notes.js from
     scripts/lib/methodology.js. DO NOT HAND-EDIT. -->
    <div class="reveal" id="anchorTables">
      <h3 style="margin-top:28px">The published anchor curves</h3>
      <p>Every intake line scores 0–100 by piecewise-linear interpolation between the fixed points below. These are the complete published recipe — the same constants the collector and the backtest use.</p>
      ${TABLES.map(([t, p, n]) => table(t, p, n)).join('\n      ')}
    </div>`;

const file = path.join(root, 'notes.html');
let html = fs.readFileSync(file, 'utf8');
if (!html.includes('id="anchorTables"')) {
  throw new Error('notes.html has no #anchorTables placeholder — add one where the tables belong');
}
if (!html.includes('<div class="reveal" id="anchorTables"></div>')) {
  throw new Error('notes.html has no empty #anchorTables div — add one where the tables belong');
}
html = html.replace('<div class="reveal" id="anchorTables"></div>', block);
fs.writeFileSync(file, html);
console.log('notes.html anchor tables regenerated:', TABLES.length, 'curves');
