#!/usr/bin/env node
/* Compile the report corpus into one readable document for editorial study.
   Source of truth stays data/reconstruction-reports.js + data/editorial.json —
   this only renders them in sequence so a human can read a year of issues the
   way a subscriber would. Rerun after backfill-reports.js.
   Output: research/editorial/trailing-year-reports.md */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, f), 'utf8');

const ctx = {window: {}};
vm.createContext(ctx);
vm.runInContext(read('data/reconstruction-reports.js'), ctx);
const recon = ctx.window.RECON_ARTICLES || [];
const live = JSON.parse(read('data/editorial.json'));

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const label = ym => {const [y,m] = ym.split('-').map(Number); return `${MONTHS[m-1]} ${y}`};

/* strip the site's bold markers; the compiled read is plain prose */
const plain = s => String(s).replace(/\*\*/g, '');

function render(a) {
  const out = [`### ${plain(a.title)}`, '', `*${plain(a.dek)}*`, '', '**Key points**'];
  a.keyPoints.forEach(k => out.push(`- ${plain(k)}`));
  out.push('');
  a.body.forEach(line => {
    if (line.startsWith('## ')) out.push(`**${plain(line.slice(3))}**`, '');
    else out.push(plain(line), '');
  });
  return out.join('\n');
}

const byMonth = new Map();
for (const a of recon) {
  if (!byMonth.has(a.month)) byMonth.set(a.month, {});
  byMonth.get(a.month)[a.slug.startsWith('recon-ward') ? 'ward' : 'house'] = a;
}
const months = [...byMonth.keys()].sort();

const doc = [];
doc.push('# The trailing-year report corpus');
doc.push('');
doc.push(`Twelve months of OOZEMeter reports, read in sequence — ${recon.length} archive`);
doc.push('reconstructions (household + Ward M per month) followed by the one report the');
doc.push('facility actually sealed live. Generated by scripts/compile-reports.js from');
doc.push('data/reconstruction-reports.js and data/editorial.json; every figure traces to');
doc.push('the public backtests. **Read it the way a subscriber would — in order, without');
doc.push('skipping** — and the identity question answers itself: what stays constant');
doc.push('across a year, what varies, where the formula shows, and where it earns its keep.');
doc.push('');
doc.push('> **What these are.** The facility opened in July 2026. Every report below dated');
doc.push("> before that is a reconstruction: today's methodology run over the latest revised");
doc.push('> public data, labeled as such in its own first paragraph. Only the final entry —');
doc.push(`> ${live.monthLabel} — was sealed live.`);
doc.push('');
doc.push('---');
doc.push('');

months.forEach((ym, i) => {
  const {house, ward} = byMonth.get(ym);
  doc.push(`## ${String(i+1).padStart(2,'0')} · ${label(ym)}`);
  doc.push('');
  if (house) { doc.push('#### The Ooze Report', ''); doc.push(render(house)); }
  else { doc.push('#### The Ooze Report', '', '*No household report — this month is a gap in the archive. A missing month stays missing.*', ''); }
  if (ward) { doc.push('#### The Ward M Report', ''); doc.push(render(ward)); }
  doc.push('---');
  doc.push('');
});

/* the live-sealed report, for contrast with the reconstructions */
doc.push('## The live seal, for contrast');
doc.push('');
doc.push(`The one report the facility published in real time (${live.monthLabel}), drafted by`);
doc.push('the story engine rather than the backfill generator. Same month as entry');
doc.push(`${String(months.length).padStart(2,'0')} above — worth reading them back to back.`);
doc.push('');
doc.push(`**Verdict line.** ${live.verdict}`);
doc.push('');
doc.push(`**Summary.** ${live.summary}`);
doc.push('');
doc.push(`**Story.** ${live.story}`);
doc.push('');
doc.push('**Line by line.**');
Object.entries(live.lines).forEach(([k, v]) => doc.push(`- ${v}`));
doc.push('');
if (live.household) doc.push(`**What a household would notice.** ${live.household}`, '');
if (live.confidence) doc.push(`**Confidence.** ${live.confidence}`, '');
doc.push(`*${live.byline}*`);
doc.push('');

fs.writeFileSync(path.join(root, 'research/editorial/trailing-year-reports.md'), doc.join('\n'));
const words = doc.join(' ').split(/\s+/).length;
console.log(JSON.stringify({status: 'pass', months: months.length, reports: recon.length + 1, words}));
